### ISSUE TITLE
Relative Paths

### ISSUE THREAD

**Issue by Lord-Kamina** [ozguncagri/nwMAME#1]
I was wondering... would it be possible to add suppport for using relative paths for the mame executable/folder/etc? As in, so it'd be possible to bundle everything (or at least the mame executable) inside the nwjs app?

**Comment by ozguncagri** [comment]
If we are talking about OS X, yes it can be possible but other operating systems (Windows and Linux) runs and keeps NWJS files differently. I have so many ideas for next releases but some of them are not applicable in Windows and Linux, but I'll consider this idea for later releases.

Thanks.

**Comment by Lord-Kamina** [comment]
Yeah, I was thinking about OSX. The app either way has some sort of check
to avoid referencing broken paths, no? I tried to manually edit the config
file but it didn't work; it just got deleted the next time I opened the app.

On Saturday, August 8, 2015, Özgün Çağrı AYDIN notifications@github.com
wrote:

> If we are talking about OS X, yes it can be possible but other operating
> systems (Windows and Linux) runs and keeps NWJS files differently. I have
> so many ideas for next releases but some of them are not applicable in
> Windows and Linux, but I'll consider this idea for later releases.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ozguncagri/nwMAME/issues/1#issuecomment-129040872.

## 

## 

  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo
- Fono: +56 9 96343643
- E-Mail: g.litenstein@gmail.com

**Comment by ozguncagri** [comment]
I said possible because it's technically possible but I wasn't implying the current code of application can do it with just editing config. App should convert the relative path to static path because it sends command for run MAME with selected game and config. That's why exact MAME executable path has to be clearly specified in that command...

**Comment by Lord-Kamina** [comment]
I see. It should be possible if you can access environment variables
though. I'm not sure but I believe recalling there were a few (in OSX) to
reference the app bundle's folder.

On Saturday, August 8, 2015, Özgün Çağrı AYDIN notifications@github.com
wrote:

> I said possible because it's technically possible but I wasn't implying
> the current code of application can do it with just editing config. App
> should convert the relative path to static path because it sends command
> for run MAME with selected game and config. That's why exact MAME
> executable path has to be clearly specified in that command...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ozguncagri/nwMAME/issues/1#issuecomment-129059333.

## 

## 

  Gregorio Litenstein Goldzweig [image: glit_qr.png] Interno de
Medicina Facultad
de Medicina Clí­nica Alemana - Universidad del Desarrollo
- Fono: +56 9 96343643
- E-Mail: g.litenstein@gmail.com

**Comment by ozguncagri** [comment]
Yeah. I wasn't tried to access NWJS bundle folder with JavaScript yet but I believe it can be solved with "hacky way" even if NWJS is not supports to direct access to bundle path.
