### ISSUE TITLE
How do I change settings for the controls?!

### ISSUE THREAD

**Issue by Eroxx** [ozguncagri/nwMAME#4]

**Comment by ozguncagri** [comment]
Actually it is not about the nwMAME. When you open the game, press **TAB** key then rest is same old MAME settings.

**Comment by Eroxx** [comment]
Ah, thanks!

And how do I list the games without pictures? Thanks!!

-- 
Eric Linder

On March 8, 2017 at 7:09:10 PM, Özgün Çağrı AYDIN (notifications@github.com)
wrote:

Actually it is not about the nwMAME. When you open the game, press *TAB*
key then rest is same old MAME settings.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ozguncagri/nwMAME/issues/4#issuecomment-285211885>, or mute
the thread

**Comment by ozguncagri** [comment]
You don't need to do anything special for listing games without pictures. Just update your game library on settings. If you don't add any cover for game it will just show CRT-like picture on cover art. Everything is described on **readme.md** file...

**Comment by Eroxx** [comment]
I’m a bit of a beginner with Github and this stuff, but slowly getting it …
Last question if you don’t mind, how do I get games to save high scores?

-- 
Eric Linder

On March 8, 2017 at 7:14:07 PM, Özgün Çağrı AYDIN (notifications@github.com)
wrote:

You don't need to do anything special for listing games without pictures.
Just update your game library on settings. If you don't add any cover for
game it will just show CRT-like picture on cover art. Everything is
described on *readme.md <http://readme.md>* file...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ozguncagri/nwMAME/issues/4#issuecomment-285212794>, or mute
the thread

**Comment by ozguncagri** [comment]
No problem :) I think games keep their high scores inside their rom dump. You should see your high scores when you open the game but I'm not exactly sure. If you want to see high scores on nwMAME's interface, it's not implemented yet...

**Edit:** I just checked and yep I can see my old scores when I open game. You don't need to do anything special. Just be sure to make your settings properly and keeping this folders and files safe for version changes and updates...

**Comment by Eroxx** [comment]
Sorry for the duplicate post - I'm not seeing high scores when I re-open a game ...

**Comment by ozguncagri** [comment]
If you want to see the scores that you recorded before using nwMAME just to be sure to move your nvram folder to Mame Output Directory that you set in nwMAME...

**Comment by Eroxx** [comment]
In my main MAME directory I don't see an nvram folder .. ? Sorry for so many questions !

**Comment by ozguncagri** [comment]
So it means you have never used mame on os x right? Because mame should create nvram folder when you open game once.

By the way don't worry about many questions. You can ask anything you want :)

**Comment by Eroxx** [comment]
Thank you so much. Truly.

So finally galaga is working (which is what I’ve spent 3 hours on). I think
the trick was finding all the right bios files.

But Dig Dug won’t work, nor arkanoid … Any hints? I’ll keep playing around
with the score thing.

-- 
Eric Linder

On March 8, 2017 at 8:14:41 PM, Özgün Çağrı AYDIN (notifications@github.com)
wrote:

So it means you have never used mame on os x right? Because mame should
create nvram folder when you open game once.

By the way don't worry about many questions. You can ask anything you want
:)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ozguncagri/nwMAME/issues/4#issuecomment-285223392>, or mute
the thread

**Comment by Eroxx** [comment]
Do these directories look right to you? I’m not sure what I was supposed to
put for devices, or what that is …

https://www.dropbox.com/s/11da95ahmpsz6ri/Screenshot%202017-03-08%2020.16.12.png?dl=0

-- 
Eric Linder

On March 8, 2017 at 8:16:05 PM, Eric Linder (eric.linder@gmail.com) wrote:

Thank you so much. Truly.

So finally galaga is working (which is what I’ve spent 3 hours on). I think
the trick was finding all the right bios files.

But Dig Dug won’t work, nor arkanoid … Any hints? I’ll keep playing around
with the score thing.

-- 
Eric Linder

On March 8, 2017 at 8:14:41 PM, Özgün Çağrı AYDIN (notifications@github.com)
wrote:

So it means you have never used mame on os x right? Because mame should
create nvram folder when you open game once.

By the way don't worry about many questions. You can ask anything you want
:)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ozguncagri/nwMAME/issues/4#issuecomment-285223392>, or mute
the thread

**Comment by ozguncagri** [comment]
You can find all bios and device files as packed on internet. If you install all bios files and device files you can run all games simply adding roms to your roms folder.

I can't see the screenshot you send me but I mentioned my folder structure (best practice for nwMAME) on readme file again :) I know I am saying all the time it's in readme file but it is :)

**Comment by Eroxx** [comment]
I just don’t understand what a device file is , as opposed to a bios or a
rom

-- 
Eric Linder

On March 8, 2017 at 8:21:49 PM, Özgün Çağrı AYDIN (notifications@github.com)
wrote:

You can find all bios and device files as packed on internet. If you
install all bios files and device files you can run all games simply adding
roms to your roms folder.

I can't see the screenshot you send me but I mentioned my folder structure
(best practice for nwMAME) on readme file again :) I know I am saying all
the time it's in readme file but it is :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ozguncagri/nwMAME/issues/4#issuecomment-285224630>, or mute
the thread

**Comment by ozguncagri** [comment]
It's like bios files but it describes devices that bioses run on it. You can find all bios files and device files on internet. I could give a link about it but I am not sure about the licensing of bios and device files so, it could be better if you find and place them to your folders :)

**Comment by Eroxx** [comment]
Oh I understand that concern, how do I distinguish between a bios file and a device file? Can I put them in the same directory just in case? Still can't get arkanoid -- got dig dug somehow. It's saying:

arkanoid    : bootstrap.bin (115 bytes) - NOT FOUND (m68705p5)
romset arkanoid is bad
1 romsets found, 0 were OK.

**Comment by ozguncagri** [comment]
Actually you can even put all bios and device files to your roms folder but it's not good practice for further updates. Separating them to folders is good for when you want to update your emulator, bioses and device files. It's just for isolating same kind of files for managing them easily...

**Comment by Eroxx** [comment]
Gotcha. Does that error mean. anything to you? That's all for now I promise!!

**Comment by ozguncagri** [comment]
This error could be cause by some bios, device or even about the rom file. Because your emulator and rom version also differs. Be sure about the rom that is specifically prepared for your emulator version...

**Comment by Eroxx** [comment]
Ok, new problem ... :) Now the program is hanging and won't open after I scanned in a large folder ....

**Comment by ozguncagri** [comment]
Yeah this is reported already. I have to change database management (and probably app experience) for fixing this issue. I am currently extremely busy and that's why I can't have time to fix it but I'll. If you want to reuse nwMAME again you have to erase NWJS caches from your user's settings folder. And large folders are not usable for current nwMAME build. Sorry :/

**Comment by Eroxx** [comment]
No problem! Can you tell me default directory of those cache folders?
Thanks so much!

-- 
Eric Linder

**Comment by ozguncagri** [comment]
It depends on your operating system. If you ware running windows it can be somewhere **c:/Users/yourUsername/AppData/Local/NWJS or nwMAME** folder. If you running on macOS it is on **~/Library/Application Support/NWJS or nwMAME** folder. If you delete this folder all your nwMAME settings will be erased and you can start it over...

**Comment by Eroxx** [comment]
Got it, thank you! 


---
L'shalom,

Rabbi Linder
Congregation Children of Israel, Athens, GA
rabbilindercci@gmail.com
www.rabbiericlinder.com




On March 9, 2017 at 9:09:30 AM, Özgün Çağrı AYDIN (notifications@github.com) wrote:

It depends on your operating system. If you ware running windows it can be somewhere c:\Users<yourUsername>\AppData\Local<NWJS or nwMAME> folder. If you running on macOS it is on ~/Libraries/Application Support/ folder. If you delete this folder all your nwMAME settings will be erased and you can start it over...
